Repository SpikeInterface/spikeinterface, pull requests merged in 2022-11, with the labels that each got.

#1052 Fixed crash with empty sorting
  spikeinterface/core/basesorting.py
  spikeinterface/core/tests/test_basesorting.py
Labels: bug

#1049 Prefer 'folder' argument and make 'zarr_path' deprecated
  spikeinterface/core/base.py
  spikeinterface/core/tests/test_baserecording.py
Labels: enhancement

#1096 Correct channel selection in tests when mono-channel recording
  spikeinterface/core/testing.py
Labels: bug

#1097 Smoother deprecation of `core.testing_tools`
  spikeinterface/core/testing_tools.py
Labels: bug

#988 motion correction
  spikeinterface/preprocessing/basepreprocessor.py
  spikeinterface/preprocessing/common_reference.py
  spikeinterface/preprocessing/preprocessing_tools.py
  spikeinterface/sortingcomponents/motion_correction.py
  spikeinterface/sortingcomponents/motion_estimation.py
  spikeinterface/sortingcomponents/tests/test_motion_correction.py
  spikeinterface/widgets/_legacy_mpl_widgets/drift.py
Labels: enhancement

#1112 Fix template_metrics select_units() and extend postprocessing tests
  spikeinterface/postprocessing/template_metrics.py
  spikeinterface/postprocessing/tests/common_extension_tests.py
Labels: bug

#1113 [docs] Update contact info and contribute pages
  doc/authors.rst
  doc/contribute.rst
Labels: documentation

#1102 Fix for sc2 on windows
  spikeinterface/sortingcomponents/clustering/clustering_tools.py
  spikeinterface/sortingcomponents/clustering/random_projections.py
Labels: bug

#1114 Add `peak_channel` as a method to `localize_peaks` in SortingComponents
  spikeinterface/postprocessing/unit_localization.py
  spikeinterface/sortingcomponents/peak_localization.py
  spikeinterface/sortingcomponents/tests/test_peak_localization.py
Labels: enhancement

#1110 Add split_job_kwargs() function
  spikeinterface/core/__init__.py
  spikeinterface/core/base.py
  spikeinterface/core/baserecording.py
  spikeinterface/core/baserecordingsnippets.py
  spikeinterface/core/job_tools.py
  spikeinterface/sorters/basesorter.py
Labels: enhancement

#1079 Add waveform extractor `save()` function and Zarr backend
  pyproject.toml
  spikeinterface/comparison/groundtruthstudy.py
  spikeinterface/comparison/hybrid.py
  spikeinterface/comparison/tests/test_hybrid.py
  spikeinterface/core/__init__.py
  spikeinterface/core/tests/test_waveform_extractor.py
  spikeinterface/core/waveform_extractor.py
  spikeinterface/postprocessing/principal_component.py
  spikeinterface/postprocessing/spike_amplitudes.py
  spikeinterface/postprocessing/tests/common_extension_tests.py
  spikeinterface/postprocessing/tests/test_correlograms.py
  spikeinterface/postprocessing/tests/test_isi.py
  spikeinterface/postprocessing/tests/test_principal_component.py
  spikeinterface/postprocessing/tests/test_spike_amplitudes.py
  spikeinterface/postprocessing/tests/test_spike_locations.py
  spikeinterface/postprocessing/tests/test_template_metrics.py
  spikeinterface/postprocessing/tests/test_template_similarity.py
  spikeinterface/postprocessing/tests/test_template_tools.py
  spikeinterface/postprocessing/tests/test_unit_localization.py
  spikeinterface/qualitymetrics/pca_metrics.py
  spikeinterface/qualitymetrics/quality_metric_calculator.py
  spikeinterface/qualitymetrics/tests/test_pca_metrics.py
  spikeinterface/sortingcomponents/matching/naive.py
Labels: enhancement

#1106 Median and average artefact
  spikeinterface/preprocessing/remove_artifacts.py
  spikeinterface/preprocessing/tests/test_remove_artifacts.py
Labels: enhancement

#1105 Refactor detect_peak() and refactor method_kwargs in components
  spikeinterface/sorters/si_based_sorters/spyking_circus2.py
  spikeinterface/sorters/si_based_sorters/tridesclous2.py
  spikeinterface/sorters/tests/test_si_based_sorters.py
  spikeinterface/sortingcomponents/matching/circus.py
  spikeinterface/sortingcomponents/matching/naive.py
  spikeinterface/sortingcomponents/matching/tdc.py
  spikeinterface/sortingcomponents/peak_detection.py
  spikeinterface/sortingcomponents/peak_localization.py
  spikeinterface/sortingcomponents/tests/test_peak_detection.py
  spikeinterface/sortingcomponents/tests/test_peak_localization.py
  spikeinterface/sortingcomponents/tools.py
Labels: enhancement
