Repository SpikeInterface/spikeinterface, pull requests merged in 2022-12, with the labels that each got.

#1061 Fixed bug in remove_duplicated_spikes with 'random' method
  spikeinterface/curation/curation_tools.py
Labels: bug

#1130 [doc] Add proper Twitter and Mastodon badges
  README.md
Labels: documentation

#1108 Port kilosort motion estimation
  spikeinterface/sortingcomponents/motion_estimation.py
  spikeinterface/sortingcomponents/peak_localization.py
  spikeinterface/sortingcomponents/tests/test_motion_estimation.py
Labels: enhancement

#1149 Refactor sorter_output folder to keep sorting metadata
  .github/workflows/full-test.yml
  conftest.py
  pyproject.toml
  spikeinterface/sorters/basesorter.py
  spikeinterface/sorters/combinato/combinato.py
  spikeinterface/sorters/hdsort/hdsort.py
  spikeinterface/sorters/herdingspikes/herdingspikes.py
  spikeinterface/sorters/ironclust/ironclust.py
  spikeinterface/sorters/kilosortbase.py
  spikeinterface/sorters/klusta/klusta.py
  spikeinterface/sorters/launcher.py
  spikeinterface/sorters/mountainsort4/mountainsort4.py
  spikeinterface/sorters/pykilosort/pykilosort.py
  spikeinterface/sorters/runsorter.py
  spikeinterface/sorters/si_based_sorters/spyking_circus2.py
  spikeinterface/sorters/si_based_sorters/tridesclous2.py
  spikeinterface/sorters/spyking_circus/spyking_circus.py
  spikeinterface/sorters/tests/common_tests.py
  spikeinterface/sorters/tests/test_combinato.py
  spikeinterface/sorters/tests/test_hdsort.py
  spikeinterface/sorters/tests/test_herdingspikes.py
  spikeinterface/sorters/tests/test_ironclust.py
  spikeinterface/sorters/tests/test_kilosort.py
  spikeinterface/sorters/tests/test_kilosort2.py
  spikeinterface/sorters/tests/test_kilosort2_5.py
  spikeinterface/sorters/tests/test_kilosort3.py
  spikeinterface/sorters/tests/test_klusta.py
  spikeinterface/sorters/tests/test_launcher.py
  spikeinterface/sorters/tests/test_mountainsort4.py
  spikeinterface/sorters/tests/test_pykilosort.py
  spikeinterface/sorters/tests/test_si_based_sorters.py
  spikeinterface/sorters/tests/test_spykingcircus.py
  spikeinterface/sorters/tests/test_tridesclous.py
  spikeinterface/sorters/tests/test_waveclus.py
  spikeinterface/sorters/tests/test_waveclus_snippets.py
  spikeinterface/sorters/tests/test_yass.py
  spikeinterface/sorters/tridesclous/tridesclous.py
  spikeinterface/sorters/waveclus/waveclus.py
  spikeinterface/sorters/waveclus/waveclus_snippets.py
  spikeinterface/sorters/yass/yass.py
Labels: enhancement

#1136 Implement ChannelSparsity object in core
  spikeinterface/core/__init__.py
  spikeinterface/core/sparsity.py
  spikeinterface/core/template_tools.py
  spikeinterface/core/tests/test_sparsity.py
  spikeinterface/core/tests/test_template_tools.py
  spikeinterface/postprocessing/__init__.py
  spikeinterface/postprocessing/template_tools.py
  spikeinterface/sorters/tests/test_si_based_sorters.py
Labels: enhancement

#1090 fsspec for streaming nwb data
  .github/workflows/s3-nwb-test.yml
  spikeinterface/extractors/nwbextractors.py
  spikeinterface/extractors/tests/test_nwb_s3_extractor.py
Labels: enhancement

#1150 Add `sorting_info` property to Sorting object
  spikeinterface/core/basesorting.py
  spikeinterface/sorters/basesorter.py
  spikeinterface/sorters/tests/common_tests.py
Labels: enhancement

#1135 giving flexibility to auto merge
  spikeinterface/curation/auto_merge.py
Labels: enhancement

#1165 [feat-widgets] Updates for SV
  spikeinterface/widgets/sorting_summary.py
  spikeinterface/widgets/sortingview/base_sortingview.py
  spikeinterface/widgets/sortingview/sorting_summary.py
Labels: enhancement

#1155 [feat-qm] Refactor QM parameter handling
  spikeinterface/qualitymetrics/__init__.py
  spikeinterface/qualitymetrics/misc_metrics.py
  spikeinterface/qualitymetrics/pca_metrics.py
  spikeinterface/qualitymetrics/quality_metric_calculator.py
  spikeinterface/qualitymetrics/quality_metric_list.py
  spikeinterface/qualitymetrics/tests/test_metrics_functions.py
  spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
Labels: enhancement

#1166 [bug-extractors] Fix neuralynx sorting function and NeoBaseSorting when no streams
  spikeinterface/extractors/neoextractors/biocam.py
  spikeinterface/extractors/neoextractors/blackrock.py
  spikeinterface/extractors/neoextractors/ced.py
  spikeinterface/extractors/neoextractors/mcsraw.py
  spikeinterface/extractors/neoextractors/neobaseextractor.py
  spikeinterface/extractors/neoextractors/neuralynx.py
  spikeinterface/extractors/neoextractors/neuroscope.py
  spikeinterface/extractors/neoextractors/nix.py
  spikeinterface/extractors/neoextractors/plexon.py
  spikeinterface/extractors/neoextractors/spikegadgets.py
  spikeinterface/extractors/neoextractors/spikeglx.py
  spikeinterface/extractors/neoextractors/tdt.py
  spikeinterface/extractors/tests/test_neoextractors.py
Labels: bug

#1163 [sparsity] Propagate sparsity to exporters
  spikeinterface/core/sparsity.py
  spikeinterface/core/waveform_extractor.py
  spikeinterface/exporters/tests/test_export_to_phy.py
  spikeinterface/exporters/to_phy.py
  spikeinterface/postprocessing/principal_component.py
Labels: enhancement

#1158 [feat-extractors] Add CellExplorerSortingExtractor
  pyproject.toml
  spikeinterface/extractors/cellexplorersortingextractor.py
  spikeinterface/extractors/extractorlist.py
  spikeinterface/extractors/tests/test_neoextractors.py
Labels: enhancement

#1159 [sparsity] Propagate sparsity to widgets
  spikeinterface/core/template_tools.py
  spikeinterface/core/waveform_extractor.py
  spikeinterface/widgets/matplotlib/unit_waveforms.py
  spikeinterface/widgets/matplotlib/unit_waveforms_density_map.py
  spikeinterface/widgets/sorting_summary.py
  spikeinterface/widgets/sortingview/metrics.py
  spikeinterface/widgets/sortingview/spike_locations.py
  spikeinterface/widgets/sortingview/unit_templates.py
  spikeinterface/widgets/spike_locations.py
  spikeinterface/widgets/spikes_on_traces.py
  spikeinterface/widgets/template_metrics.py
  spikeinterface/widgets/template_similarity.py
  spikeinterface/widgets/tests/test_widgets.py
  spikeinterface/widgets/unit_depths.py
  spikeinterface/widgets/unit_summary.py
  spikeinterface/widgets/unit_waveforms.py
  spikeinterface/widgets/unit_waveforms_density_map.py
  spikeinterface/widgets/utils.py
Labels: enhancement

#1142 [bug-qm] Refactor amplitude_cutoff and presence_ratio metrics
  spikeinterface/core/__init__.py
  spikeinterface/core/generate.py
  spikeinterface/core/segmentutils.py
  spikeinterface/curation/auto_merge.py
  spikeinterface/curation/tests/test_auto_merge.py
  spikeinterface/curation/tests/test_remove_redundant.py
  spikeinterface/curation/tests/test_sortingview_curation.py
  spikeinterface/qualitymetrics/misc_metrics.py
  spikeinterface/qualitymetrics/tests/test_metrics_functions.py
  spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
  spikeinterface/widgets/tests/test_widgets.py
Labels: bug

#1164 [sparsity] Start estimate_sparsity() function.
  .github/workflows/s3-nwb-test.yml
  pyproject.toml
  spikeinterface/core/__init__.py
  spikeinterface/core/basesorting.py
  spikeinterface/core/template_tools.py
  spikeinterface/core/tests/test_waveform_extractor.py
  spikeinterface/core/waveform_extractor.py
  spikeinterface/curation/auto_merge.py
  spikeinterface/extractors/cellexplorersortingextractor.py
  spikeinterface/extractors/extractorlist.py
  spikeinterface/extractors/neoextractors/biocam.py
  spikeinterface/extractors/neoextractors/blackrock.py
  spikeinterface/extractors/neoextractors/ced.py
  spikeinterface/extractors/neoextractors/mcsraw.py
  spikeinterface/extractors/neoextractors/neobaseextractor.py
  spikeinterface/extractors/neoextractors/neuralynx.py
  spikeinterface/extractors/neoextractors/neuroscope.py
  spikeinterface/extractors/neoextractors/nix.py
  spikeinterface/extractors/neoextractors/plexon.py
  spikeinterface/extractors/neoextractors/spikegadgets.py
  spikeinterface/extractors/neoextractors/spikeglx.py
  spikeinterface/extractors/neoextractors/tdt.py
  spikeinterface/extractors/nwbextractors.py
  spikeinterface/extractors/tests/test_neoextractors.py
  spikeinterface/extractors/tests/test_nwb_s3_extractor.py
  spikeinterface/qualitymetrics/__init__.py
  spikeinterface/qualitymetrics/misc_metrics.py
  spikeinterface/qualitymetrics/pca_metrics.py
  spikeinterface/qualitymetrics/quality_metric_calculator.py
  spikeinterface/qualitymetrics/quality_metric_list.py
  spikeinterface/qualitymetrics/tests/test_metrics_functions.py
  spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
  spikeinterface/sorters/basesorter.py
  spikeinterface/sorters/tests/common_tests.py
  spikeinterface/widgets/sorting_summary.py
  spikeinterface/widgets/sortingview/base_sortingview.py
  spikeinterface/widgets/sortingview/sorting_summary.py
Labels: enhancement

#1153 [feat-exp] Optimizing Phy-based extractors
  spikeinterface/extractors/phykilosortextractors.py
Labels: enhancement
