Repository SpikeInterface/spikeinterface, pull requests merged in 2023-01, with the labels that each got.

#1171 [bug-core] Use absolute folder in NpySnippetsFolder
  spikeinterface/core/npyfoldersnippets.py
Labels: bug

#1172 [bug-preprocessing] Fix phase-shift dtype
  spikeinterface/extractors/phykilosortextractors.py
  spikeinterface/preprocessing/phase_shift.py
  spikeinterface/preprocessing/tests/test_phase_shift.py
Labels: bug

#1183 [feat-sc] Refactor motion_estimate
  spikeinterface/sortingcomponents/motion_estimation.py
  spikeinterface/sortingcomponents/tests/test_motion_estimation.py
Labels: sortingcomponents

#1152 [feat-core] Handle sparsity inside WaveformExtractor [sparsity]
  .github/workflows/full-test.yml
  examples/modules/core/plot_4_waveform_extractor.py
  spikeinterface/core/__init__.py
  spikeinterface/core/sparsity.py
  spikeinterface/core/template_tools.py
  spikeinterface/core/tests/test_sparsity.py
  spikeinterface/core/tests/test_template_tools.py
  spikeinterface/core/tests/test_waveform_extractor.py
  spikeinterface/core/waveform_extractor.py
  spikeinterface/exporters/tests/test_export_to_phy.py
  spikeinterface/exporters/to_phy.py
  spikeinterface/postprocessing/principal_component.py
  spikeinterface/postprocessing/template_metrics.py
  spikeinterface/postprocessing/tests/common_extension_tests.py
  spikeinterface/postprocessing/tests/test_principal_component.py
  spikeinterface/qualitymetrics/pca_metrics.py
  spikeinterface/qualitymetrics/tests/test_metrics_functions.py
  spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
  spikeinterface/widgets/matplotlib/unit_waveforms.py
  spikeinterface/widgets/matplotlib/unit_waveforms_density_map.py
  spikeinterface/widgets/sorting_summary.py
  spikeinterface/widgets/sortingview/metrics.py
  spikeinterface/widgets/sortingview/spike_locations.py
  spikeinterface/widgets/sortingview/unit_templates.py
  spikeinterface/widgets/spike_locations.py
  spikeinterface/widgets/spikes_on_traces.py
  spikeinterface/widgets/template_metrics.py
  spikeinterface/widgets/template_similarity.py
  spikeinterface/widgets/tests/test_widgets.py
  spikeinterface/widgets/unit_depths.py
  spikeinterface/widgets/unit_summary.py
  spikeinterface/widgets/unit_waveforms.py
  spikeinterface/widgets/unit_waveforms_density_map.py
  spikeinterface/widgets/utils.py
Labels: enhancement

#1201 [bug-installation] Fix check install
  installation_tips/check_your_install.py
Labels: bug

#1198 [feat-extractors] Add option to load synchronized timestamps in OpenEphys
  spikeinterface/extractors/neoextractors/openephys.py
  spikeinterface/extractors/tests/test_neoextractors.py
Labels: enhancement

#1199 [fix-postprocessing/qm] Quality metrics and postprocessing fixes for sparsity and global job_kwargs
  spikeinterface/core/globals.py
  spikeinterface/core/sparsity.py
  spikeinterface/core/tests/test_globals.py
  spikeinterface/exporters/tests/test_export_to_phy.py
  spikeinterface/postprocessing/principal_component.py
  spikeinterface/postprocessing/template_metrics.py
  spikeinterface/postprocessing/tests/common_extension_tests.py
  spikeinterface/postprocessing/tests/test_principal_component.py
  spikeinterface/postprocessing/tests/test_template_metrics.py
  spikeinterface/postprocessing/tests/test_unit_localization.py
  spikeinterface/postprocessing/unit_localization.py
  spikeinterface/qualitymetrics/misc_metrics.py
  spikeinterface/qualitymetrics/pca_metrics.py
  spikeinterface/qualitymetrics/quality_metric_calculator.py
  spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
  spikeinterface/widgets/tests/test_widgets.py
Labels: bug

#1177 [feat-qm] Implement missing metrics (amplitude median, drift metrics)
  doc/api.rst
  doc/index.rst
  doc/quality_metrics/amp_median.rst
  doc/quality_metrics/amplitude_cutoff.rst
  doc/quality_metrics/amplitude_median.rst
  doc/quality_metrics/cumulative_drift.rst
  doc/quality_metrics/drift.rst
  doc/quality_metrics/maximum_drift.rst
  spikeinterface/postprocessing/spike_amplitudes.py
  spikeinterface/qualitymetrics/misc_metrics.py
  spikeinterface/qualitymetrics/pca_metrics.py
  spikeinterface/qualitymetrics/quality_metric_calculator.py
  spikeinterface/qualitymetrics/quality_metric_list.py
  spikeinterface/qualitymetrics/tests/test_metrics_functions.py
  spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
Labels: enhancement

#1207 [feat-sorters] Set n_jobs to None for sorters to propagate global job kwargs
  spikeinterface/core/globals.py
  spikeinterface/core/job_tools.py
  spikeinterface/core/tests/test_globals.py
  spikeinterface/postprocessing/spike_amplitudes.py
  spikeinterface/sorters/basesorter.py
  spikeinterface/sorters/si_based_sorters/spyking_circus2.py
  spikeinterface/sorters/si_based_sorters/tridesclous2.py
Labels: enhancement

#1204 [feat-extractors] Streaming IBL recordings
  pyproject.toml
  spikeinterface/core/baserecordingsnippets.py
  spikeinterface/extractors/cbin_ibl.py
  spikeinterface/extractors/extractorlist.py
  spikeinterface/extractors/neoextractors/spikeglx.py
  spikeinterface/extractors/stream_ibl.py
  spikeinterface/extractors/tests/test_stream_ibl.py
Labels: enhancement

#1221 Noise level as a waveform extractor extention
  spikeinterface/postprocessing/__init__.py
  spikeinterface/postprocessing/noise_level.py
  spikeinterface/postprocessing/tests/common_extension_tests.py
  spikeinterface/postprocessing/tests/test_noise_levels.py
Labels: enhancement, postprocessing

#1224 Protect against QM returning None
  spikeinterface/qualitymetrics/quality_metric_calculator.py
Labels: bug, qualitymetrics

#1025 Add IBL channel interpolation to preprocessing
  pyproject.toml
  spikeinterface/preprocessing/interpolate_bad_channels.py
  spikeinterface/preprocessing/preprocessing_tools.py
  spikeinterface/preprocessing/preprocessinglist.py
  spikeinterface/preprocessing/tests/test_interpolate_bad_channels.py
Labels: enhancement, preprocessing

#1230 Correctly find parent folders for concatenate recording/sorting objects
  spikeinterface/core/core_tools.py
Labels: bug, container, core

#1222 Promote distinctipy color as a second choice because it is slow.
  spikeinterface/widgets/_legacy_mpl_widgets/__init__.py
  spikeinterface/widgets/tests/test_widgets_utils.py
  spikeinterface/widgets/utils.py
Labels: enhancement, widgets

#1233 Testing `test_s3_nwb_fsspec` caching
  conftest.py
  spikeinterface/extractors/nwbextractors.py
  spikeinterface/extractors/tests/test_nwb_s3_extractor.py
Labels: refactor, testing

#1143 RemoveArtifactsRecording with amplitude scaling and time jittering
  spikeinterface/core/waveform_tools.py
  spikeinterface/preprocessing/filter.py
  spikeinterface/preprocessing/remove_artifacts.py
  spikeinterface/preprocessing/tests/test_remove_artifacts.py
Labels: preprocessing

#1209 Initial refactoring for node pipeline
  spikeinterface/sortingcomponents/features_from_peaks.py
  spikeinterface/sortingcomponents/peak_detection.py
  spikeinterface/sortingcomponents/peak_localization.py
  spikeinterface/sortingcomponents/peak_pipeline.py
  spikeinterface/sortingcomponents/tests/test_motion_estimation.py
  spikeinterface/sortingcomponents/tests/test_peak_detection.py
  spikeinterface/sortingcomponents/tests/test_peak_localization.py
  spikeinterface/sortingcomponents/tests/test_peak_pipeline.py
  spikeinterface/sortingcomponents/tests/test_template_matching.py
Labels: enhancement, sortingcomponents
