Repository SpikeInterface/spikeinterface, pull requests merged in 2025-09, with the labels that each got.

#4111 Update deprecated cuda import
  pyproject.toml
  src/spikeinterface/sorters/utils/misc.py
Labels: dependencies, packaging, deprecations

#4105 Fix typos and buggy code in modules docs
  doc/how_to/customize_a_plot.rst
  doc/how_to/handle_drift.rst
  doc/how_to/physical_units.rst
  doc/modules/benchmark.rst
  doc/modules/comparison.rst
  doc/modules/core.rst
  doc/modules/curation.rst
  doc/modules/extractors.rst
  doc/modules/generation.rst
  doc/modules/motion_correction.rst
  doc/modules/postprocessing.rst
  doc/modules/preprocessing.rst
  doc/modules/sorters.rst
  doc/modules/sortingcomponents.rst
  doc/modules/widgets.rst
Labels: documentation, Harvard Docathon 2025

#4080 Alter how quality metrics check extension dependencies
  doc/modules/postprocessing.rst
  doc/modules/qualitymetrics.rst
  src/spikeinterface/core/tests/test_sortinganalyzer.py
  src/spikeinterface/qualitymetrics/misc_metrics.py
  src/spikeinterface/qualitymetrics/quality_metric_calculator.py
  src/spikeinterface/qualitymetrics/quality_metric_list.py
  src/spikeinterface/qualitymetrics/tests/conftest.py
  src/spikeinterface/qualitymetrics/tests/test_metrics_functions.py
  src/spikeinterface/qualitymetrics/tests/test_quality_metric_calculator.py
  src/spikeinterface/qualitymetrics/utils.py
Labels: qualitymetrics

#4123 Check install ci - use uv
  .github/workflows/installation-tips-test.yml
  installation_tips/check_your_install.py
Labels: continuous integration

#4143 Add gpu requirements to rtsort
  src/spikeinterface/sorters/external/rt_sort.py
Labels: sorters

#4138 Improve docs for curation module and model
  doc/api.rst
  doc/conf.py
  pyproject.toml
  src/spikeinterface/core/sorting_tools.py
  src/spikeinterface/core/sortinganalyzer.py
  src/spikeinterface/curation/auto_merge.py
  src/spikeinterface/curation/curation_format.py
  src/spikeinterface/curation/curation_model.py
  src/spikeinterface/curation/tests/sv-sorting-curation-int.json
  src/spikeinterface/curation/tests/sv-sorting-curation-str.json
  src/spikeinterface/curation/tests/test_sortingview_curation.py
  src/spikeinterface/extractors/neoextractors/openephys.py
Labels: documentation
