Repository SpikeInterface/spikeinterface, pull requests merged in 2025-07, with the labels that each got.

#4023 Fix uniqueness of locations in test_average_across_directions
  src/spikeinterface/preprocessing/tests/test_average_across_direction.py
  src/spikeinterface/preprocessing/tests/test_depth_order.py
Labels: bug, testing

#4027 Ignore AppleDouble format files on analyzer extension load
  src/spikeinterface/core/sortinganalyzer.py
Labels: bug

#4005 Allow `run_sorter` to accept dicts
  doc/how_to/process_by_channel_group.rst
  doc/modules/sorters.rst
  src/spikeinterface/core/loading.py
  src/spikeinterface/sorters/runsorter.py
  src/spikeinterface/sorters/tests/test_runsorter.py
Labels: enhancement

#4030 Fix NeuroNexus stream_id
  src/spikeinterface/extractors/tests/test_neoextractors.py
Labels: NEO

#4051 Remove MEArec downloads from docs
  doc/how_to/read_various_formats.rst
  doc/how_to/read_various_formats_files/read_various_formats_12_0.png
  doc/how_to/read_various_formats_files/read_various_formats_12_1.png
  doc/modules/comparison.rst
  doc/tutorials_custom_index.rst
  examples/how_to/read_various_formats.py
  examples/tutorials/core/plot_4_sorting_analyzer.py
  examples/tutorials/qualitymetrics/plot_3_quality_metrics.py
  examples/tutorials/qualitymetrics/plot_4_curation.py
  examples/tutorials/widgets/plot_3_waveforms_gallery.py
  examples/tutorials/widgets/plot_4_peaks_gallery.py
Labels: documentation, Harvard Docathon 2025

#4046 Add lower bound version to numba
  pyproject.toml
Labels: dependencies

#4052 Switch RTD to UV
  docs_rtd.yml
  readthedocs.yml
Labels: documentation, Harvard Docathon 2025

#4057 Add motion functions to api docs
  doc/api.rst
  doc/how_to/handle_drift.rst
  examples/how_to/handle_drift.py
  src/spikeinterface/preprocessing/motion.py
Labels: documentation, Harvard Docathon 2025

#4025 Fix soft vs hard merge issue in analyzer
  src/spikeinterface/core/sortinganalyzer.py
Labels: bug, core

#4035 Add multi-segment capability to BaseRasterWidget and children
  src/spikeinterface/widgets/amplitudes.py
  src/spikeinterface/widgets/motion.py
  src/spikeinterface/widgets/rasters.py
  src/spikeinterface/widgets/tests/test_widgets_utils.py
  src/spikeinterface/widgets/utils.py
Labels: widgets

#4064 Add `read_neuroscope` to `__all__` for extractors
  src/spikeinterface/extractors/extractor_classes.py
Labels: packaging

#4062 Use Github token to help with Windows Testing
  .github/workflows/all-tests.yml
  .github/workflows/full-test-with-codecov.yml
Labels: continuous integration

#4065 typo: ephsy -> ephys
  src/spikeinterface/extractors/neoextractors/openephys.py
Labels: documentation

#4060 Check for remote paths in check_paths_relative
  src/spikeinterface/core/core_tools.py
Labels: core

#4033 More deprecation updates for version 0.103.0
  src/spikeinterface/benchmark/benchmark_plot_tools.py
  src/spikeinterface/comparison/multicomparisons.py
  src/spikeinterface/comparison/tests/test_multisortingcomparison.py
  src/spikeinterface/core/loading.py
  src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
  src/spikeinterface/curation/auto_merge.py
  src/spikeinterface/extractors/cbin_ibl.py
  src/spikeinterface/extractors/neoextractors/openephys.py
  src/spikeinterface/extractors/nwbextractors.py
  src/spikeinterface/extractors/tests/test_nwbextractors.py
  src/spikeinterface/sorters/launcher.py
  src/spikeinterface/sortingcomponents/peak_pipeline.py
  src/spikeinterface/sortingcomponents/tests/test_waveforms/test_waveform_thresholder.py
  src/spikeinterface/widgets/sorting_summary.py
Labels: deprecations

#4024 Fix sampling rate issue when aggregating
  src/spikeinterface/core/tests/test_unitsaggregationsorting.py
  src/spikeinterface/core/unitsaggregationsorting.py
Labels: core

#3503 Installation tips using uv
  installation_tips/README.md
  installation_tips/beginner_conda_env_stable.yml
  installation_tips/beginner_requirements_rolling.txt
  installation_tips/beginner_requirements_stable.txt
  installation_tips/check_your_install.py
  installation_tips/cleanup_for_windows.py
  installation_tips/full_spikeinterface_environment_linux_dandi.yml
  installation_tips/full_spikeinterface_environment_rolling_updates.yml
  installation_tips/full_spikeinterface_environment_windows.yml
Labels: packaging

#3597 Implemented RT-Sort as an external sorter
  doc/modules/sorters.rst
  doc/references.rst
  src/spikeinterface/sorters/external/rt_sort.py
  src/spikeinterface/sorters/external/tests/test_rtsort.py
  src/spikeinterface/sorters/sorterlist.py
Labels: sorters

#3817 Add splitting functionality to curation and `SortingAnalyzer`
  src/spikeinterface/core/__init__.py
  src/spikeinterface/core/analyzer_extension_core.py
  src/spikeinterface/core/sorting_tools.py
  src/spikeinterface/core/sortinganalyzer.py
  src/spikeinterface/core/tests/test_sortinganalyzer.py
  src/spikeinterface/curation/curation_format.py
  src/spikeinterface/curation/curation_model.py
  src/spikeinterface/curation/tests/test_curation_format.py
  src/spikeinterface/postprocessing/amplitude_scalings.py
  src/spikeinterface/postprocessing/correlograms.py
  src/spikeinterface/postprocessing/isi.py
  src/spikeinterface/postprocessing/principal_component.py
  src/spikeinterface/postprocessing/spike_amplitudes.py
  src/spikeinterface/postprocessing/spike_locations.py
  src/spikeinterface/postprocessing/template_metrics.py
  src/spikeinterface/postprocessing/template_similarity.py
  src/spikeinterface/postprocessing/tests/test_multi_extensions.py
  src/spikeinterface/postprocessing/unit_locations.py
  src/spikeinterface/qualitymetrics/quality_metric_calculator.py
Labels: curation

#4079 Add missing functions in API
  doc/api.rst
  src/spikeinterface/preprocessing/interpolate_bad_channels.py
Labels: documentation

#4036 Templates.is_scaled > Templates.is_in_uV
  src/spikeinterface/benchmark/tests/common_benchmark_testing.py
  src/spikeinterface/core/analyzer_extension_core.py
  src/spikeinterface/core/sparsity.py
  src/spikeinterface/core/template.py
  src/spikeinterface/core/template_tools.py
  src/spikeinterface/core/tests/test_template_class.py
  src/spikeinterface/core/tests/test_template_tools.py
  src/spikeinterface/generation/drift_tools.py
  src/spikeinterface/generation/drifting_generator.py
  src/spikeinterface/generation/tests/test_drift_tools.py
  src/spikeinterface/postprocessing/localization_tools.py
  src/spikeinterface/sorters/internal/tridesclous2.py
  src/spikeinterface/sortingcomponents/clustering/circus.py
  src/spikeinterface/sortingcomponents/clustering/position_and_features.py
  src/spikeinterface/sortingcomponents/clustering/random_projections.py
  src/spikeinterface/sortingcomponents/clustering/tools.py
  src/spikeinterface/sortingcomponents/tools.py
  src/spikeinterface/widgets/drift_templates.py
Labels: core

#4072 Add IBL's "noise cutoff" quality metric (again)
  doc/modules/qualitymetrics/example_cutoff.png
  doc/modules/qualitymetrics/noise_cutoff.rst
  doc/references.rst
  src/spikeinterface/qualitymetrics/misc_metrics.py
  src/spikeinterface/qualitymetrics/quality_metric_list.py
  src/spikeinterface/qualitymetrics/tests/test_metrics_functions.py
Labels: qualitymetrics

#4055 Add working with tetrodes doc
  doc/conf.py
  doc/how_to/index.rst
  doc/how_to/process_by_channel_group.rst
  examples/how_to/working_with_tetrodes.py
  examples/tutorials/forhowto/README.rst
  examples/tutorials/forhowto/plot_1_working_with_tetrodes.py
Labels: documentation, Harvard Docathon 2025

#4074 Add `to_pynapple_tsgroup` function
  doc/modules/exporters.rst
  pyproject.toml
  src/spikeinterface/exporters/__init__.py
  src/spikeinterface/exporters/tests/test_export_to_pynapple.py
  src/spikeinterface/exporters/to_pynapple.py
Labels: exporters

#3719 Expose gather mode to tridesclous2 and spykingcircus2
  src/spikeinterface/core/node_pipeline.py
  src/spikeinterface/sorters/internal/spyking_circus2.py
  src/spikeinterface/sorters/internal/tests/test_spykingcircus2.py
  src/spikeinterface/sorters/internal/tests/test_tridesclous2.py
  src/spikeinterface/sorters/internal/tridesclous2.py
  src/spikeinterface/sortingcomponents/matching/main.py
Labels: sorters

#4077 Add archived sorters and change rt-sort to rtsort
  doc/modules/sorters.rst
  doc/references.rst
  src/spikeinterface/sorters/container_tools.py
  src/spikeinterface/sorters/external/rt_sort.py
  src/spikeinterface/sorters/runsorter.py
  src/spikeinterface/sorters/sorterlist.py
Labels: sorters

#4096 Small bug in plot benchmark label order when grouping
  src/spikeinterface/benchmark/benchmark_plot_tools.py
Labels: benchmarks

#4097 Fix `plot_amplitudes` for sortingview
  src/spikeinterface/widgets/amplitudes.py
Labels: widgets
